/**
 * Generate V2__seed_categories.sql from categories.csv
 * Usage: node server/db/scripts/csv-to-sql.js
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const csvPath = path.resolve(__dirname, "../../categories.csv");
const outPath = path.resolve(__dirname, "../migrations/V2__seed_categories.sql");

const csv = fs.readFileSync(csvPath, "utf-8");
const lines = csv.trim().split("\n").slice(1); // skip header

const rows = lines.map((line) => {
  const [id, ...rest] = line.split(",");
  const name = rest.join(",").trim();
  // Escape single quotes for SQL
  const escaped = name.replace(/'/g, "''");
  return `  (${id.trim()}, '${escaped}')`;
});

const sql = `-- V2__seed_categories.sql — 305 categories from categories.csv
-- Generated by server/db/scripts/csv-to-sql.js — do not edit manually
INSERT INTO categories (id, name) VALUES
${rows.join(",\n")}
ON CONFLICT (id) DO NOTHING;

-- Reset sequence so next insert doesn't collide
SELECT setval('categories_id_seq', (SELECT MAX(id) FROM categories));
`;

fs.writeFileSync(outPath, sql, "utf-8");
console.log(`Wrote ${rows.length} categories to ${outPath}`);
